default_config:
system_health:

frontend:
  themes: !include_dir_merge_named themes

lovelace:
  mode: storage

sun:
weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key

bmw_connected_drive:
  name:
    username: !secret bmw_connected_id
    password: !secret bmw_connected_secret
    region: north_america

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
 
badnest:
 issue_token: !secret badnest_issue_token
 cookie: !secret badnest_cookie
 region: us

climate:
  - platform: badnest
    scan_interval: 10

camera:
  - platform: badnest
  
sensor:
  - platform: badnest
  - platform: google_wifi
    host: 10.0.0.1
    name: Google Wifi
  - platform: openweathermap
    api_key: !secret owm_api_key
    monitored_conditions:
      - temperature
      - humidity
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: disk_free
        arg: /
      - type: disk_use
        arg: /
      - type: processor_use
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
      - 'beat'
  - platform: template
    sensors:
      battery_pixel:
        friendly_name: Pixel 4 XL Charging Status
        unit_of_measurement: '%'
        value_template: >-
          {%- if state_attr('sensor.pixel_4_xl_battery_level', 'is_charging') %}
            is_charging
          {% else %}
            not_charging
          {% endif %}
        device_class: battery
      battery_samsung:
        friendly_name: Samsung Note Charging Status
        unit_of_measurement: '%'
        value_template: >-
          {%- if state_attr('sensor.sm_n950u_battery_level', 'is_charging') %}
            is_charging
          {% else %}
            not_charging
          {% endif %}
        device_class: battery

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_secret
    
http:
  base_url: !secret http_base_url
  cors_allowed_origins:
    - https://cast.home-assistant.io
    
upnp:
  port_mapping: true
  local_ip: 10.0.0.3
  sensors: true

media_player:
  - platform: onkyo
    host: 10.0.0.193
    name: Onkyo

speedtestdotnet:
  monitored_conditions:
    - ping
    - download
    - upload
  server_id: 13086

tts:
  - platform: google_translate
    time_memory: 60
    service_name: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml